# Generated by Django 5.2.17 on 2026-09-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_is_estimate",
            field=models.BooleanField(
                default=False,
                help_text="Marca esta opción si el precio es una referencia y debe cotizarse (típico en servicios).",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("material", "Material / producto"),
                    ("service", "Servicio / paquete"),
                ],
                default="material",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Para servicios, usar el precio 'desde' o base de la cotización.",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, help_text="Solo aplica a materiales/productos físicos."
            ),
        ),
    ]
