# Generated by Django 5.2.17 on 2026-09-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_price_is_estimate_product_product_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                choices=[
                    ("floor", "Pisos"),
                    ("tile", "Enchapes"),
                    ("paint", "Pintura"),
                    ("wall", "Muros / drywall"),
                    ("roof", "Cubiertas / azoteas"),
                    ("waterproof", "Impermeabilización"),
                    ("tools", "Herramientas"),
                    ("remodel", "Remodelación integral"),
                ],
                default="tools",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="short_pitch",
            field=models.CharField(
                blank=True,
                help_text="Frase corta para la card de servicios en el home.",
                max_length=140,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="show_as_service",
            field=models.BooleanField(
                default=True,
                help_text="Mostrar esta categoría en la sección de servicios del home.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="specs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Ficha técnica como pares clave-valor, ej. {'Resistencia': 'PEI 4', 'Formato': '60x60 cm'}",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                blank=True,
                default="unidad",
                help_text="Unidad de venta: m², galón, unidad, caja, etc.",
                max_length=30,
            ),
        ),
    ]
