# Generated by Django 5.2.17 on 2026-09-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=250)),
                ("body", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="pages/"),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("show_in_nav", models.BooleanField(default=True)),
                ("nav_order", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nav_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Aplideco S.A.S.", max_length=120),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("primary_color", models.CharField(default="#0F172A", max_length=7)),
                ("accent_color", models.CharField(default="#22D3EE", max_length=7)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("whatsapp_number", models.CharField(blank=True, max_length=30)),
                ("address", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Configuración del sitio",
                "verbose_name_plural": "Configuración del sitio",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("tiktok", "TikTok"),
                            ("whatsapp", "WhatsApp"),
                            ("youtube", "YouTube"),
                            ("linkedin", "LinkedIn"),
                            ("x", "X (Twitter)"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
