# Generated by Django 5.2.17 on 2026-09-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "badge",
                    models.ImageField(
                        blank=True, null=True, upload_to="certifications/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_handled", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("residencial", "Residencial"),
                            ("comercial", "Comercial"),
                            ("industrial", "Industrial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=150)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "sqm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="m² intervenidos"
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-year"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="clients_satisfied",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="projects_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="sqm_built",
            field=models.PositiveIntegerField(
                default=0, verbose_name="m² construidos/intervenidos"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="years_experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="accent_color",
            field=models.CharField(default="#FF5A1F", max_length=7),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="primary_color",
            field=models.CharField(default="#1A1A1A", max_length=7),
        ),
    ]
