# Generated by Django 5.2.17 on 2026-09-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_certification_contactrequest_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Foto real de obra/proyecto para el hero del home (reemplaza el fondo de marcador de posición).",
                null=True,
                upload_to="branding/",
            ),
        ),
    ]
